### ISSUE TITLE
Xây dựng giao diện, thân thiện với người dùng, đơn giản có tính tương tác cao, tích hợp được một số chức năng cơ bản

### ISSUE THREAD

**Issue by eleven1308** [WeGroup123456/ProjectWeb#11]
Xây dựng giao diện trang cá nhân người dùng, dòng thời gian , trang ảnh , và các trang liên quan

**Comment by QuynhPhuong** [comment]
Liệt kê rõ các trang cần làm. Tớ có thể giúp xd giao diện.

**Comment by ducdh-dev** [comment]
Giao diện phải làm cẩn thận mời phát triển dễ được
