### ISSUE TITLE
Xây dựng database

### ISSUE THREAD

**Issue by QuynhPhuong** [WeGroup123456/ProjectWeb#12]
Các trường: 
+users: id, username, password, email, liked_recipes, short_description, total_post, created_at, updated_at
+recipes: id, name, category_id, images, description, ingredients, user_id, total_like, created_at, updated_at
+category: id, name

Bạn nào có đề xuất thêm hay bớt, sửa các trường thì đề xuất. Đây là các trường tạm thời.

**Comment by ducdh-dev** [comment]
Database khó đây, còn phải nghĩ

**Comment by ducdh-dev** [comment]
Đức và Quỳnh sẽ đảm nhận Database này

**Comment by ducdh-dev** [comment]
![cnpm_database](https://user-images.githubusercontent.com/29506281/32173122-85dca19a-bdb0-11e7-8a34-40215de29bd6.png)

Khung Database

1 user có nhiều bình luận
1 post có nhiều bình luận
1 user bình luận nhiều post

1 user like nhiều post, mỗi post <=1 like
1 post có nhiều like

1 user có thể follow nhiều user khác
1 user có thể có nhiều người follow

**Comment by QuynhPhuong** [comment]
bảng post p có ảnh hiện ở giao diện vs ảnh chi tiết. Nội dung bài post nữa chứ

**Comment by ducdh-dev** [comment]
Mới là cái khung, nhìn là phải biết chứ lị :))

**Comment by QuynhPhuong** [comment]
Ô thì cái khung nên mới bảo bổ sung chỗ này chỗ kia chớ ai biết c bổ sung hay k

**Comment by ducdh-dev** [comment]
![cnpm_database](https://user-images.githubusercontent.com/29506281/32480489-ae4a8554-c3c1-11e7-9b42-93219e54daf7.png)
Update

**Comment by ducdh-dev** [comment]
![image](https://user-images.githubusercontent.com/29506281/33330934-d1776858-d492-11e7-8815-a598be4fb92c.png)
