### ISSUE TITLE
Sprint: Lập project Laravel, tạo model, kết nối giữa các model ( tháng 11 )

### ISSUE THREAD

**Issue by ducdh-dev** [WeGroup123456/ProjectWeb#17]

**Comment by ducdh-dev** [comment]
Đã hoàn thiện và upcode lên github

**Comment by ducdh-dev** [comment]
Phân công:
Đức: Giay
Quỳnh Phương: User
Cầm Phan Hồ: Brand
Đoàn Thức: Slide
Hoàng Gia: Loaigiay
Nhữ Dũng: Baohanh

**Comment by ducdh-dev** [comment]
Mọi người tìm hiểu commit lên github, sử dụng github desktop để clone project về và commit không cần nhớ lệnh git

**Comment by eleven1308** [comment]
Sẽ upload từng chức năng một theo cách phân công nhé
