### ISSUE TITLE
Sprint: Thêm sửa xóa cho Hãng giày, loại giày, Slide, Comment, Giày, Bảo hành (tuần 1 tháng 12)

### ISSUE THREAD

**Issue by ducdh-dev** [WeGroup123456/ProjectWeb#18]

**Comment by ducdh-dev** [comment]
Đã thêm phần xem danh sách giày

**Comment by ducdh-dev** [comment]
Tất cả mọi người code test trước ngon rồi hãng commit lên nhé

**Comment by thucdv** [comment]
Ok

**Comment by ducdh-dev** [comment]
Hạn cuối là ngày mai, test cẩn thận rồi hãng up code lên

**Comment by ducdh-dev** [comment]
Mạng FPT đang ngu Github anh em chịu khó ra quán làm nhé

**Comment by ducdh-dev** [comment]
Phân công:
Đức: Giay
Quỳnh Phương: User
Cầm Phan Hồ: Brand
Đoàn Thức: Slide
Hoàng Gia: Loaigiay
Nhữ Dũng: Baohanh

**Comment by camphanho** [comment]
ok
