### ISSUE TITLE
Sử dụng Laravel

### ISSUE THREAD

**Issue by ducdh-dev** [WeGroup123456/ProjectWeb#2]

**Comment by ducdh-dev** [comment]
Ai chưa học Laravel thì inbox mình nhé

**Comment by camphanho** [comment]
tôi chưa học laravel nhé

**Comment by ducdh-dev** [comment]
Chưa học laravel thì có thể giao nhiệm vụ phần giao diện

**Comment by thucdv** [comment]
Mọi người giao cho t làm phần thiết kế giao diện đi, tại t chỉ ms bắt đầu học lập trình web thôi. Chưa có kinh nghiệm j cả. Thanks

**Comment by ducdh-dev** [comment]
Ok
