### ISSUE TITLE
Tìm hiểu OpenLayers. Tích hợp bản đồ, hiển thị các cơ sở của shop

### ISSUE THREAD

**Issue by QuynhPhuong** [WeGroup123456/ProjectWeb#22]
Học tại đây: https://openlayers.org/en/latest/examples/

**Comment by ducdh-dev** [comment]
Đức và Quỳnh phụ trách phần này

**Comment by QuynhPhuong** [comment]
trình tự này:
_Tạo array chứa các shop obj
_Khởi tạo source vector chứa các feature: var vectorIcon = new ol.source.Vector({});
_Khởi tạo style cho các feature: var iconStyle = new ol.style.Style({...})
_Lặp các obj trong array
  +Tạo feature và gắn data từ obj:  var iconFeature = new ol.Feature({..})
  +Set style cho feature: iconFeature.setStyle(iconStyle)
  +add feature vào source vector: vectorIcon.addFeature(iconFeature);
_Tạo layer vector và add source vào: var vectorLayer= new ol.layer.Vector({...})
_Add Layer vector vào map: map.addLayer(vectorLayer);
tất cả đưa vào hàm get_fields

**Comment by QuynhPhuong** [comment]
chỉ đường đến cửa hàng gần nhất
![bando](https://user-images.githubusercontent.com/32598364/33870462-79008746-df40-11e7-82b8-5aa3104dd3e5.png)

**Comment by eleven1308** [comment]
Cái này trong của cái của t có làm rồi nên chỉ cần tích hợp cái  cần thiết vào là được
