### ISSUE TITLE
Phân công công việc từ nay tới deadline

### ISSUE THREAD

**Issue by ducdh-dev** [WeGroup123456/ProjectWeb#26]
Dự kiến công việc tiếp theo cho tới deadline:
Đức, Quỳnh Phương: Đổ giao diện, làm thuật toán cho các chức năng bán hàng.
Cầm Phan Hồ: Nắm chắc lí thuyết của scrum master.
Hoàng Gia Đoàn Thức Nhữ Dũng: Tìm hiểu và làm phpunit test trên project laravel.

**Comment by QuynhPhuong** [comment]
ok

**Comment by eleven1308** [comment]
OK

**Comment by anhdung081994** [comment]
oke
