### ISSUE TITLE
Web chia sẻ công thức nấu ăn

### ISSUE THREAD

**Issue by QuynhPhuong** [WeGroup123456/ProjectWeb#4]
Mỗi người dùng đăng kí 1 account.
Giao diện gần giống insta, đơn giản.
Giao diện người dùng có 1 vài chức năng đơn giản như post bài, tìm kiếm công thức.
Khi chọn post bài. Người dùng phải điền vào 1 vài trường bắt buộc như: tên công thức, nguyên liệu, có option chọn loại món ăn, và textarea điền công thức. 1 vài trường không bắt buộc mình tạm nghĩ ra là ảnh món ăn. Trước hết là 2 chức năng lớn đó.

**Comment by ducdh-dev** [comment]
Ý kiến hay nhóm sẽ có thể phát triển theo hướng này
