### ISSUE TITLE
Thảo luận ý tưởng

### ISSUE THREAD

**Issue by ducdh-dev** [WeGroup123456/ProjectWeb#5]

**Comment by ducdh-dev** [comment]
Ý tưởng làm một cái về hướng dẫn nấu ăn có vẻ ổn và ít đụng hàng

**Comment by QuynhPhuong** [comment]
hướng là website để người dùng chia sẻ. Nội dung chia sẻ là gì mọi người vote nhé

**Comment by ducdongki** [comment]
Chia sẻ về công thức nấu ăn có vẻ gần gũi và dễ tương tác nhiều người dùng

**Comment by camphanho** [comment]
web đi, vì team chắc ai cũng biết, hoặc là làm ứng dụng quản lý cái j đó bằng java cũng được.

**Comment by ducdh-dev** [comment]
Web thôi, ứng dụng quản lý làm chán rồi =))

**Comment by anhdung081994** [comment]
làm web về nấu ăn cũng được đó
