### ISSUE TITLE
website tương tác mạng xã hội, kết bạn , theo dõi, post bài, tìm kiếm, thích bài viết và bình luận

### ISSUE THREAD

**Issue by eleven1308** [WeGroup123456/ProjectWeb#7]
Website mạng xã hội cơ bản, gồm các list ảnh ở trang người dùng cá nhân, và gồm các list ảnh trên dòng thời gian, ở đó người dùng có thể xem được cái bài viết mà người dùng đã kết bạn, hover thêm các tính năng bình luận, like

**Comment by ducdh-dev** [comment]
Sẽ khoai đây
