### ISSUE TITLE
app hỗ trợ học từ mới tiếng anh bằng cách mở khóa màn hình hoặc mở khóa ứng dụng trên smart phone

### ISSUE THREAD

**Issue by camphanho** [WeGroup123456/ProjectWeb#8]
từ mới sẽ được nhập vào có dạng: từ tiếng anh : nghĩa tiếng việt
khi mở khóa sẽ hiện ra nghĩa tiếng việt , phải điền từ tiếng anh thì mới mở được hoặc ngược lại.

**Comment by ducdh-dev** [comment]
Phải làm web thôi vì không ai biết androi

**Comment by nguyenbs** [comment]
Em nào làm được Javascript tốt không? Học code ReactNative đi
